name: Helm Diff Commment
description: Post a PR comment with a helm diff.
inputs:
  diff-content:
    description: The diff output
    required: true
  environment-name:
    description: Name of the environment.
    required: true
  pr-number:
    description: The number of pull request
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - name: Create comment message
      shell: bash
      id: create-comment-message
      run: |
        cat <<EOF >> "${GITHUB_OUTPUT}"
        message<<EOM
        ## Environment: ${{ inputs.environment-name }}

        <details>
        <summary>
        helmfile diff output
        </summary>

        \`\`\`diff
        ${{ inputs.diff-content }}
        \`\`\`
        
        </details>
        EOM
        EOF

    - name: Get pull request number
      if: github.ref_name == github.event.repository.default_branch
      uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |
          const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner: "${{ github.repository_owner }}",
            repo: "${{ github.repository }}".split("/").pop(),
            commit_sha: "${{ github.sha }}",
          });
          return response.data.pop().number;

    - name: Comment pull request using PR number
      if: github.ref_name == github.event.repository.default_branch
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.create-comment-message.outputs.message }}
        pr-number: ${{ steps.my-script.outputs.result }}

    - name: Comment pull request
      if: github.ref_name != github.event.repository.default_branch
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.create-comment-message.outputs.message }}    
    
