name: Helm Action Comment
description: Post a comment message with a Helm output on a pull request associated with the corresponding Helm action.
inputs:
  helm-output:
    description: The Helm action output
    required: true
  environment-name:
    description: Name of the environment
    required: true
  helm-action:
    description: The name of the helm action that produces the output
    required: true  

outputs: {}
runs:
  using: composite
  steps:
    - name: Create comment message
      shell: bash
      id: create-comment-message
      run: |
        cat <<EOF >> "${GITHUB_OUTPUT}"
        message<<EOM
        ## Environment: ${{ inputs.environment-name }}

        <details>
        <summary>
        Helm ${{ inputs.helm-action }} output
        </summary>

        \`\`\`diff
        ${{ inputs.helm-output }}
        \`\`\`
        
        </details>
        EOM
        EOF

    - name: Get pull request number
      if: github.ref_name == github.event.repository.default_branch
      uses: actions/github-script@v7
      id: get-pr-number
      continue-on-error: true
      with:
        result-encoding: string
        retries: 3
        script: |
          const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner: "${{ github.repository_owner }}",
            repo: "${{ github.repository }}".split("/").pop(),
            commit_sha: "${{ github.sha }}",
          });
          if (response.data.length != 0) {
            let prNumber = response.data.pop().number;
            return prNumber;
          }
          else {
            throw new Error(
              "Could not find pull request associated with the latest commit. Someone must have committed directly to the default branch ;("
            );
          }
          
    - name: Comment pull request using PR number
      if: ${{ github.ref_name == github.event.repository.default_branch && steps.get-pr-number.outcome != failure }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.create-comment-message.outputs.message }}
        pr_number: ${{ steps.get-pr-number.outputs.result }}

    - name: Comment pull request
      if: github.ref_name != github.event.repository.default_branch
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.create-comment-message.outputs.message }}    
    
